# Generated by Django 4.1.3 on 2022-12-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_images_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
